
included:
  - Example
  - ../KindeAuthSwift
excluded:
  # Third-party
  - Pods
  # Generated
  - ../KindeAuthSwift/Classes/KindeManagementApi

disabled_rules:
  # Match default XCode formatting
  - trailing_whitespace
  - line_length