
included:
  - Example
  - ../KindeSDK
excluded:
  # Third-party
  - Pods
  # Generated
  - ../KindeSDK/Classes/KindeManagementAPI

disabled_rules:
  # Match default XCode formatting
  - trailing_whitespace
  - line_length