name: KindeSDK
targets:
  KindeSDK:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [KindeSDK]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: 
